# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class WindowLogin(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(341, 296)
        MainWindow.setMinimumSize(QtCore.QSize(330, 270))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/B_Karkhanin/Pictures/logo1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(
            "background-color: qconicalgradient(cx:1, cy:0, angle:0,"
            " stop:0 rgba(0, 0, 0, 255), stop:1 rgba(100, 187, 250, 255));\n"
            "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("text-align: center;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(230, 170))
        self.frame.setMaximumSize(QtCore.QSize(800, 800))
        self.frame.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.frame.setAcceptDrops(True)
        self.frame.setStyleSheet("background-color: rgb(70, 132, 176);\n"
                                 "width: 60%;\n"
                                 "margin-left: 30%;\n"
                                 "margin-right: 30%;\n"
                                 "border-radius: 12px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(-1, 10, 10, -1)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(2440, 1280))
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
                                 "text-align: center;\n"
                                 "color: rgb(0, 0, 255);height:40%;font-size:15vh;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/B_Karkhanin/Pictures/logo1.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.line_login = QtWidgets.QLineEdit(self.frame)
        self.line_login.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.line_login.setFont(font)
        self.line_login.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "height:25%;\n"
                                      "border: 2px solid white;\n"
                                      "border-radius: 12px;\n"
                                      "font-family:\'Montserrat\';\n"
                                      "font-size:11pt")
        self.line_login.setText("")
        self.line_login.setAlignment(QtCore.Qt.AlignCenter)
        self.line_login.setPlaceholderText("Логин")
        self.line_login.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.line_login.setClearButtonEnabled(False)
        self.line_login.setObjectName("line_login")
        self.verticalLayout.addWidget(self.line_login)

        self.line_password = QtWidgets.QLineEdit(self.frame)
        self.line_password.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.line_password.setFont(font)
        self.line_password.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "height:25%;\n"
                                         "font-family:\'Montserrat\';\n"
                                         "font-size:11pt;\n"
                                         "border: 2px solid white;\n"
                                         "border-radius: 12px;")
        self.line_password.setText("")
        self.line_password.setPlaceholderText("Пароль")
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setAlignment(QtCore.Qt.AlignCenter)
        self.line_password.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.line_password)

        self.button_login = QtWidgets.QPushButton(self.frame)
        self.button_login.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_login.setFont(font)
        self.button_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_login.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "height:25%;\n"
                                        "font-family:\'Montserrat\';\n"
                                        "font-size: 11pt;\n"
                                        "border: 2px solid white;\n"
                                        "border-radius: 12px;")
        self.button_login.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.button_login)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslate_ui(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslate_ui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BZ document flow"))
        self.label.setWhatsThis(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.button_login.setText(_translate("MainWindow", "Войти"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = WindowLogin()
    ui.setup_ui(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
