# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tree.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        # self.treeWidget = my_tree_widget.MyTreeWidget()

        self.treeWidget.expandAll()
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.viewport().setAcceptDrops(True)
        self.treeWidget.setDropIndicatorShown(True)

        self.treeWidget.setObjectName("treeWidget")
        # self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        # self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)

        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setToolTip(1, "")
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(
            QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDropEnabled | QtCore.Qt.ItemIsUserCheckable)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setToolTip(0, "")
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.verticalLayout.addWidget(self.treeWidget)

        # self.push_print_hierarchy = QtWidgets.QPushButton()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "2"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "zgdb"))
        self.treeWidget.topLevelItem(0).setFlags(
            QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsDropEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled | QtCore.Qt.ItemIsEditable)
        # self.treeWidget.topLevelItem(0).
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "400"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "235"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "401"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Новый дочерний элемент"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "402"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "260"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "291"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
