"""database creation

Revision ID: 4507e9565b49
Revises: 
Create Date: 2023-08-28 15:13:26.155159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4507e9565b49'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins_data',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=False),
    sa.Column('date_creating', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('last_name', 'name', 'patronymic', name='_uq_admin_name')
    )
    op.create_table('departments',
    sa.Column('name_department', sa.String(length=100), nullable=False),
    sa.Column('number_department', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=True),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('super_admin_flag', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('date_last_changes_password', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['admins_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('salt')
    )
    op.create_table('departments_hierarchy',
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_data',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('patronymic', sa.String(length=40), nullable=False),
    sa.Column('date_creating', sa.DateTime(), nullable=False),
    sa.Column('id_department', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['admins_data.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_department'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('last_name', 'name', 'patronymic', name='_uq_user_name')
    )
    op.create_table('data_about_documents',
    sa.Column('inner_number', sa.String(length=100), nullable=False),
    sa.Column('output_number', sa.String(length=100), nullable=False),
    sa.Column('output_date', sa.DateTime(), nullable=False),
    sa.Column('type_document', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_creating', sa.DateTime(), nullable=False),
    sa.Column('id_creator', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_creator'], ['users_data.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=True),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('date_last_changes_password', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('salt')
    )
    op.create_table('files_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['data_about_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files_documents')
    op.drop_table('users_login')
    op.drop_table('data_about_documents')
    op.drop_table('users_data')
    op.drop_table('departments_hierarchy')
    op.drop_table('admins_login')
    op.drop_table('departments')
    op.drop_table('admins_data')
    # ### end Alembic commands ###
