name: Python PyQt CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  DRIVER_DB: ${{ secrets.DRIVER_DB }}
  DIALECT_DB: ${{ secrets.DIALECT_DB }}
  LOGIN_DB: ${{ secrets.LOGIN_DB }}
  PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
  NAME_DB: ${{ secrets.NAME_DB }}
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }}
  HASH_FUNCTION: ${{ secrets.HASH_FUNCTION }}

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Unit tests
        run: |
          pytest -v src/tests/unit_tests
      - name: Func tests
        run: |
          cd ..
          echo "Working directory is $(pwd)"
          pytest -v src/tests/func_tests

